#!/usr/bin/env ruby

require_relative "../lib/faa_auth"
require "highline/import"

domain = ask("Enter your faa domain: ") { |q|
  q.echo = true
  q.default = FaaInfo.domain
}
login = ask("Enter your #{domain} username: ") { |q| q.echo = true }
passwd = ask("Enter your FAA Access pin : ") { |q| q.echo = "*" }
sec1 = ask("Enter security question1: ") { |q| q.echo = true }
ans1 = ask("Enter security answer1: ") { |q| q.echo = true }
sec2 = ask("Enter security question2: ") { |q| q.echo = true }
ans2 = ask("Enter security answer2: ") { |q| q.echo = true }
sec3 = ask("Enter security question3: ") { |q| q.echo = true }
ans3 = ask("Enter security answer3: ") { |q| q.echo = true }

salt = ask("Enter your salt: ") { |q|
  q.default = FaaAuth::Converter.default_salt
  q.echo = true
}


raise "Empty login or password" if login.to_s.size == 0 || passwd.to_s.size == 0

converter = FaaAuth::Converter.new(salt)

puts "Put the following lines in .env"
puts
puts "FAA_DOMAIN=#{domain}"
puts "FAA_USERNAME_CODE=#{converter.encode(login)}"
puts "FAA_ACCESS_PIN=#{converter.encode(passwd)}"
puts "FAA_SECURITY_QUESTION1=#{converter.encode(sec1)}"
puts "FAA_SECURITY_ANSWER1=#{converter.encode(ans1)}"
puts "FAA_SECURITY_QUESTION2=#{converter.encode(sec2)}"
puts "FAA_SECURITY_ANSWER2=#{converter.encode(ans2)}"
puts "FAA_SECURITY_QUESTION3=#{converter.encode(sec3)}"
puts "FAA_SECURITY_ANSWER3=#{converter.encode(ans3)}"

puts "FAA_CODE_SALT=#{salt}"

# Which city were you born in?
# Where did you first meet your spouse?
# What is your pet's name?
